[审核] Properties By IceNature
DlangRen/Programming-in-D pull request #67
Opened 2016-11-10 10:28 UTC by IceNature

2016-12-01 14:41 UTC, meatatt requested changes
辛苦了！加油

2016-12-01 14:41 UTC, meatatt commented on ddili/src/ders/d.cn/property.d
> +在学习分片的时候我们已经多次用到它。slice 的 $(C length) 属性返回了其包含元素的个数：
`slice`（`slices`）不译

2016-12-01 14:41 UTC, meatatt commented on ddili/src/ders/d.cn/property.d
> +$(H5 读属性)
建议直译为`返回值的属性函数`
`读属性`有歧义，此处应为`属性函数`

2016-12-01 14:41 UTC, meatatt commented on ddili/src/ders/d.cn/property.d
> +$(H5 写属性)
同上，建议直译为`用于赋值的属性函数`

2016-12-01 14:41 UTC, meatatt commented on ddili/src/ders/d.cn/property.d
> +和 slices 的 $(C length) 属性一样，用户定义的属性也可以用于赋值：
译文中不译的部分需尊重中文习惯，名词使用一致的单数形式。
`slices` => `slice`

2016-12-01 14:41 UTC, meatatt commented on ddili/src/ders/d.cn/property.d
> +和 slices 的 $(C length) 属性一样，用户定义的属性也可以用于赋值：
译文中不译的部分需尊重中文习惯，名词使用一致的单数形式。
`slices` => `slice`

2016-12-01 14:41 UTC, meatatt commented on ddili/src/ders/d.cn/property.d
> +之前我们通过定义属性为 $(C Rectangle) 添加了“第三个变量”。当然，除了属性普通，成员函数也可以实现我们需要的功能：
标点错位
`当然，除了属性，普通成员函数也可以实现我们需要的功能`

2016-12-02 13:36 UTC, IceNature commented
@meatatt 已修正

2017-03-19 08:19 UTC, meatatt approved these changes

2017-03-19 08:23 UTC, merged